/**
 * Created by Lost_RD on 3/03/2015.
 */

package com.lostrd.regionalores;

import cpw.mods.fml.common.Mod;
import cpw.mods.fml.common.event.FMLInitializationEvent;
import cpw.mods.fml.common.event.FMLPostInitializationEvent;
import cpw.mods.fml.common.event.FMLPreInitializationEvent;

@Mod(modid="RegionalOres", name="Regional Ores", version="1.0")

public class RegionalOres
{
    @Mod.Instance("RegionalOres")
    public static RegionalOres instance;

    @Mod.EventHandler
    public void preInit(FMLPreInitializationEvent event)
    {
        event.getModMetadata().autogenerated = false;
        event.getModMetadata().version = "1.0"; // Version setting
        event.getModMetadata().name = "Regional Ores"; // Name setting
        event.getModMetadata().description = "Generates one ore deposit per biome which means you need to travel to find every ore but once you find it you're all set because the deposits are pretty big to compensate for their rarity."; // Description setting
        event.getModMetadata().authorList.add("lost_RD"); // Adding my name to the mod's author list
        event.getModMetadata().credits = "Dreamed up and coded by lost_RD";
        //event.getModMetadata().logoFile = "/path/to/your/logo/file/location/logo_file_name.png" // Setting the logo file location
    }

    @Mod.EventHandler
    public void init(FMLInitializationEvent event)
    {

    }

    public void postInit(FMLPostInitializationEvent event)
    {

    }

}
