package com.lostrd.regionalores;

/**
 * Created by lost_RD on 3/03/2015.
 */

import com.lostrd.regionalores.configuration.ConfigurationHandler;
import com.lostrd.regionalores.proxy.IProxy;
import com.lostrd.regionalores.reference.Reference;
import cpw.mods.fml.common.Mod;
import cpw.mods.fml.common.SidedProxy;
import cpw.mods.fml.common.event.FMLInitializationEvent;
import cpw.mods.fml.common.event.FMLPostInitializationEvent;
import cpw.mods.fml.common.event.FMLPreInitializationEvent;

@Mod(modid= Reference.MOD_ID, name=Reference.MOD_NAME, version=Reference.VERSION)

public class RegionalOres
{
    @Mod.Instance(Reference.MOD_ID)
    public static RegionalOres instance;

    @SidedProxy(clientSide = Reference.CLIENT_PROXY_CLASS, serverSide = Reference.SERVER_PROXY_CLASS)
    public static IProxy proxy;

    @Mod.EventHandler
    public void preInit(FMLPreInitializationEvent event)
    {
        event.getModMetadata().autogenerated = false;
        event.getModMetadata().version = Reference.VERSION; // Version setting
        event.getModMetadata().name = Reference.MOD_NAME; // Name setting
        event.getModMetadata().description = "Generates one ore deposit per biome which means you need to travel to find every ore but once you find it you're all set because the deposits are pretty big to compensate for their rarity."; // Description setting
        event.getModMetadata().authorList.add("lost_RD"); // Adding my name to the mod's author list
        event.getModMetadata().credits = "Dreamed up and coded by lost_RD";
        //event.getModMetadata().logoFile = "/path/to/your/logo/file/location/logo_file_name.png" // Setting the logo file location

        ConfigurationHandler.init(event.getSuggestedConfigurationFile());
    }

    @Mod.EventHandler
    public void init(FMLInitializationEvent event)
    {

    }

    public void postInit(FMLPostInitializationEvent event)
    {

    }

}
